# don't modify this section!
DEFAULT:
  perform_check: yes  # should the check be performed?
  # Sections setting this to 'no' don't need to include any other options as they are ignored
  # When a file is using a section with the option set to 'no', no checks are performed.

  # what licenses (or license expressions) are allowed for files in this section
  # when setting this option in a section, you need to list all the allowed licenses
  allowed_licenses:
    - Apache-2.0
  license_for_new_files: Apache-2.0  # license to be used when inserting a new copyright notice
  new_notice_c: |  # notice for new C, CPP, H, HPP and LD files
    /*
     * SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
     *
     * SPDX-License-Identifier: {license}
     */
  new_notice_python: |  # notice for new python files
    # SPDX-FileCopyrightText: {years} Espressif Systems (Shanghai) CO LTD
    # SPDX-License-Identifier: {license}

  # comment lines matching:
  # SPDX-FileCopyrightText: year[-year] Espressif Systems
  # or
  # SPDX-FileContributor: year[-year] Espressif Systems
  # are replaced with this template prefixed with the correct comment notation (# or // or *) and SPDX- notation
  espressif_copyright: '{years} Espressif Systems (Shanghai) CO LTD'

# this section sets the default license for examples and unit tests of components
examples_and_unit_tests:
  include:
   - 'components/**/examples/**'
   - 'components/**/test/**'
   - 'components/**/tests/**'
   - 'common_components/**'
  allowed_licenses:
  - Apache-2.0
  - Unlicense
  - CC0-1.0
  license_for_new_files: Unlicense OR CC0-1.0

asio_component:
  include:
    - 'components/asio/port/**'
  allowed_licenses:
    - Apache-2.0
    - BSL-1.0

slim_modem_examples:
  include:
    - 'examples/esp_netif/slip_custom_netif/**'
  allowed_licenses:
    - Apache-2.0
    - Unlicense
    - CC0-1.0

ignore:
  perform_check: no
  include:
   - 'components/**/docs/**'
   - 'components/esp_modem/port/linux/**'
   - 'components/asio/examples/**'
   - 'components/mdns/**/esp_system_protocols_linux/**'
   - 'common_components/protocol_examples_common/**'
