name: "net_connect: build-tests"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build_net_connect:
    if: contains(github.event.pull_request.labels.*.name, 'net_connect') || github.event_name == 'push'
    name: Build
    strategy:
      matrix:
        idf_ver: ["latest", "release-v5.4", "release-v6.0"]
        idf_target: ["esp32"]
        test: [ { app: net_connect_example, path: "components/net_connect/examples/net_connect_example"}, { app: ppp_connect_example, path: "components/net_connect/examples/ppp_connect_example"}]
        include:
          - idf_ver: "latest"
            warning: "the choice symbol ETHERNET_PHY_LAN867X\nis deprecated: Please use smi_gpio instead"

    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout esp-protocols
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build ${{ matrix.test.app }} with IDF-${{ matrix.idf_ver }} for ${{ matrix.idf_target }}
        env:
          EXPECTED_WARNING: ${{ matrix.warning }}
        shell: bash
        working-directory: ${{matrix.test.path}}
        run: |
          . ${IDF_PATH}/export.sh
          pip install idf-component-manager idf-build-apps --upgrade
          python ../../../ci/build_apps.py . --target ${{ matrix.idf_target }} -vv --preserve-all --pytest-app
